apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: i7pll6693-go
  janus-idp.io/tekton: i7pll6693-go
  backstage.io/kubernetes-id: i7pll6693-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: i7pll6693-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
